name: Build and Push Container
on:
  workflow_dispatch:
    inputs:
      rhoasVersion:
        description: 'Release version of the rhoas CLI'     
        required: true
        default: 'error' 
        type: string
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: ./build-docker-container.sh
        env:
          RHOAS_VERSION: ${{ github.event.inputs.rhoasVersion }}
  push:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Quay.io
        run: docker login quay.io --username $QUAY_USERNAME --password $QUAY_PASSWORD
        env:
          QUAY_USERNAME: ${{ secrets.quayUsername }}
          QUAY_PASSWORD: ${{ secrets.quayPassword }}
      - name: Push to Quay.io
        run: ./push-to-registry.sh
        env:
          RHOAS_VERSION: ${{ github.event.inputs.rhoasVersion }}
        
