name: Build and Push Container
on:
  workflow_dispatch:
    inputs:
      rhoasVersion:
        description: 'Release version of the rhoas CLI'     
        required: true
        default: 'error' 
        type: string
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: |
          docker build --build-arg RHOAS_VERSION=$RHOAS_VERSION --rm -t quay.io/rhoas/tools .
          docker tag quay.io/rhoas/tools:$RHOAS_VERSION quay.io/rhoas/tools:$RHOAS_VERSION
        env:
          RHOAS_VERSION: ${{ github.event.inputs.rhoasVersion }}
  push:
    depends-on: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Quay.io
        run: docker login quay.io --username $QUAY_USERNAME --password $QUAY_PASSWORD
        env:
          QUAY_USERNAME: ${{ secrets.quayUsername }}
          QUAY_PASSWORD: ${{ secrets.quayPassword }}
      - id: Push to Quay.io
        run: |
          docker push quay.io/rhoas/tools
          docker push quay.io/rhoas/tools:$TAG
        env:
          TAG: ${{ github.event.inputs.rhoasVersion }}
        